### PR TITLE
Skip .lmp to allow loading external images.

### PR DESCRIPTION
**Pull request by dsvensson**

### CODE REVIEW

**Comment by dsvensson** [comment]
Not sure what the comment in the plugin API refers to:

> _//wad image is ONLY for loading out of q1 gfx.wad. loads a shader. use gfx/foo.lmp for hud stuff._

Another broken thing is that it only works if a map has already been loaded. If issuing `plug_load ezhud` from console before a map has started, the lmp images will be used instead.

**Comment by Shpoike** [comment]
'Another broken thing is that it only works if a map has already been loaded'
I assume you're expecting the cursed ezquake behaviour - specifying 'gfx/foo' and expecting it to load eg 'wad/foo.png' instead.
Such weird hacks are present in fte via fallback loaders - eg the Shader_Default2D generator in this case - but that special-case crap is not exposed via the plugin system.
Just put your textures in the proper places instead.

**Comment by eukara** [comment]
Removing the .lmp is fine however and the primary intent of this PR

**Comment by dsvensson** [comment]
@Shpoike No, I'm only talking about a vid_restart unloading the image that was loaded before vid_restart.

**Comment by Shpoike** [comment]
those lines match ones inside the engine-proper.
if you do a vid_restart WITHOUT the plugin then you get the engine's equivalents with the same names, with textures loaded from the alternative paths. if you then load the plugin (which uses the same shader names) then it just uses the ones the engine already loaded.
if you do a vid_restart WITH the plugin loaded, the engine skips its normal sbar startup and doesn't bother to create any of those shaders. the plugin then reloads and tries loading them, fails to add the extra ezquake-specific 'wad' subdir, and you get no replacement textures.

Like I said, the easy fix is to just move your replacement gfx textures to the gfx subdir instead of the wad subdir (which wad? are these meant to be wall textures? oh noes!). This change will of course help compat with other engines too, but then it wouldn't be 'EZ'hud if its not using weird random texture paths...
Probably what you want to do is to tweak the drawfuncs->LoadImage function to accept some flags to behave more like the csqc precache_pic function does, potentially also allowing it to download them as required, too.

**Comment by dsvensson** [comment]
Aha ok. But why load the images from the wrong place in the first case? Why the inconsistency?

**Comment by Shpoike** [comment]
gl_font,c Font_GetTrackerImage has a Image_GetTexture call. adding the IF_NOPURGE flag should help prevent those tracker images going missing when images get flushed.
I assume this has been an issue since r_keepimages changed its default to 0.

**Pull request merged**
